Fixed bug with combining m2wsgi and webob:
The problem is that webob converts the request body environ['wsgi.input']
into a FakeCGIBody object which does not implement the close() method.

Traceback (most recent call last):
  File "/home/example/env/lib/python2.7/site-packages/gevent/greenlet.py    def __init__(self,*args,**kwds):
", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/example/env/src/m2wsgi/m2wsgi/io/gevent.py", line 220, in do_handle_request
    self.process_request(req)
  File "/home/example/env/src/m2wsgi/m2wsgi/io/base.py", line 953, in process_request
    environ["wsgi.input"].close()
AttributeError: 'FakeCGIBody' object has no attribute 'close'
<Greenlet at 0x2e63c00: do_handle_request> failed with AttributeError